### ISSUE TITLE
Period::split() return Sequence

### ISSUE THREAD

**Issue by mariosimao** [thephpleague/period#102]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | yes

#### Proposal

Would be nice if  `Period::split()` returned a `Sequence` instead of an iterable.

With a `Sequence`, we have all the features from an iterable and more.

**Comment by nyamsprod** [comment]
@mariosimao this is indeed scheduled for the next major release 😉
