### ISSUE TITLE
Is v3.x still stable and secure for PHP >=5.6 compatible environments (WP Plugins)

### ISSUE THREAD

**Issue by danieliser** [thephpleague/period#108]
Version  ^3

### Question
Looking to use this but our plugin for WordPress still has at least enough 5.6 users to not be able to use the latest. In the mean time while we push them to update, would using the older documented version 3 be sufficient?

**Comment by nyamsprod** [comment]
v3 is no longer maintain so the answer is I don't know. The code can still be reviewed  but I would not recommend it's use because if bugs or security issues are found they won't be fixed at least not in this repository.
