### ISSUE TITLE
Number of (over)nights

### ISSUE THREAD

**Issue by strarsis** [thephpleague/period#110]
How can the number of overnights inside an interval be found out?
`%a` returns 0 when the interval doesn't contain a whole day, but a night (00:00 AM) between.

Example code to reproduce the issue:
```php
<?php
require 'vendor/autoload.php';
use League\Period\Period;

$period1 = new Period( new DateTime('2020-10-04 00:00', new DateTimeZone('UTC')), new DateTime('2020-12-18 00:00', new DateTimeZone('UTC')), Period::INCLUDE_ALL );
$period2 = new Period( new DateTime('2020-10-05 16:00', new DateTimeZone('UTC')), new DateTime('2020-10-06 12:00', new DateTimeZone('UTC')), Period::INCLUDE_ALL );
$diff    = $period2->intersect( $period1 );
$nights  = (int) $diff->getDateInterval()->format( '%a' );
var_dump( $nights ); // 0
````

**Comment by nyamsprod** [comment]
@strarsis thanks for using the library but the question you are asking is more about how to use `DateInterval` than how to use  `League\Period` . To be honest I would not consider using a `DateInterval` object for that as per definition it has no knowledge of  date and time ...  I would suggest using some kind of filter of some kind. How to create that filter I'll leave that excercise to you.

**Comment by strarsis** [comment]
@nyamsprod: Indeed! I now solved the issue by first setting one of the Period ends to 00:00 or 23.59 so even with an interval over two abutting days, the DateInterval would be >24, hence a full day is counted.

**Comment by strarsis** [comment]
@nyamsprod: Is there a function in PHP League Period library that equal to the function `startOfDay` of the [PHP Carbon library](https://carbon.nesbot.com/docs/)?
Just setting one end of period to 00:00 can still cause issues with DST for example.
