### ISSUE TITLE
Return type not compatible with PHP8

### ISSUE THREAD

**Issue by eastern-ravindra** [thephpleague/period#137]
### Bug Report

_(Fill in the relevant information below to help triage your issue.)_

| Information | Description |
|--------------|---------|
| 4.12.0 |  |
| PHP 8.2 |  |
| OS Platform |  |

#### Summary

league/period:4.12.0 supports PHP8.2 as per documentation mentioned in https://packagist.org/packages/league/period#4.12.0
But It is giving below error
```
During inheritance of DateTimeImmutable: Uncaught ErrorException: Return type of League\Period\Datepoint::createFromMutable($datetime): League\Period\Datepoint should either be compatible with DateTimeImmutable::createFromMutable(DateTime $object): static, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

As mentioned in th error, we should add #[\ReturnTypeWillChange] attribute for createFromMutable method to work with PHP8

```
/**
     * @inheritDoc
     *
     * @param DateTime $datetime
     *
     * @return static
     */
    public static function createFromMutable($datetime): self
    {
        return self::create(parent::createFromMutable($datetime));
    }
```
needs to be changed to 
```
/**
     * @inheritDoc
     *
     * @param DateTime $datetime
     *
     * @return static
     */
    #[ReturnTypeWillChange]
    public static function createFromMutable($datetime): self
    {
        return self::create(parent::createFromMutable($datetime));
    }
```

**Comment by nyamsprod** [comment]
@eastern-ravindra thanks for using the package and for your report unfortunately, `league/period` v4 is no longer supported as explained on [the documentation website](https://period.thephpleague.com/):

> Once a new major version is released, the previous stable release remains supported for six more months with patches and security fixes.

If you find the same issue on the current stable version which also supports PHP8.2 I will gladly fix it.
