### ISSUE TITLE
HHVM compliance

### ISSUE THREAD

**Issue by nyamsprod** [thephpleague/period#14]
New tests were added after testing the period package against @padraic [humbug](https://github.com/padraic/humbug). The package received bug fixes but tests no longer work on HHVM.

**Comment by padraic** [comment]
This is not my fault :P

**Comment by nyamsprod** [comment]
I know must be some hidden or HHVM edge case but I would have to test each test individually to narrow the bug

**Comment by nyamsprod** [comment]
Just run a travis check . As guessed the problem is with HHVM but I'm kinda lost as to why since PHP since to not mind at all ?

**Comment by nyamsprod** [comment]
I finally did caught my HHVM bug :+1: 
http://3v4l.org/HQKnj
HHVM and PHP do not treat the same way a misform dateinterval this is an inconsistency.
