### ISSUE TITLE
adding a named constructor with DatePeriod

### ISSUE THREAD

**Issue by nyamsprod** [thephpleague/period#15]
in PHP 5.6 series `DatePeriod` [was improved](https://bugs.php.net/bug.php?id=68268) with the following getter methods
-  `DatePeriod::getStartDate`
-  `DatePeriod::getEndDate`
-  `DatePeriod::getDateInterval`

Should be interesting to have named constructors on `Period` that could return a new `Period` instance from a `DatePeriod` object

**Comment by nyamsprod** [comment]
This will be ok to add when PHP5.6 and or PHP7 will be more used

**Comment by seyfer** [comment]
@nyamsprod everybody uses PHP 7.1 now. It's time
