### ISSUE TITLE
Formatting dates

### ISSUE THREAD

**Issue by barryvdh** [thephpleague/period#23]
I'm not sure if this is possible within the scope of this project, or not wanted. But I didn't find it in the docs:

Is it possible to format the period 'nicely'? Something like this:

 - 2015-07-01 - 2015-07-03: 'July 1,2,3 2015'
 - 2015-07-01 - 2015-07-05: 'July 1-5 2015'
 - 2015-07-25 - 2015-08-05: 'July 25 - August 5 2015'
 - 2015-12-25 - 2016-01-05: 'December 25 2015 - January 5 2016'

Not sure about the syntax or localisation, but what do you think about something like this? Could be useful for showing dates in a event calendar etc.

**Comment by nyamsprod** [comment]
I think this is out of scope for the package... currently the package provides the ISO8601 representation of a period as well as the start and end date as DateTimeInterface objects. If you want other formatting representations you should check other libraries that do decorate DateTimeInterface objects to offer that. The first that come to mind is Carbon of course.
