### ISSUE TITLE
Opposite to diff

### ISSUE THREAD

**Issue by blomdahldaniel** [thephpleague/period#29]
Hey! This is a really cool package! 

I was reading your API for comparison and found `diff()`. Diff it is **awesome!!** And with diff, I thought that there must be some opposite of diff? So `diff()` returns the period that was before, and the period that was after. Wouldnt it make sence to have a function for the opposite? So the function would return the (math description `union`) time of the period that is overlapped?

I might just be a bit dumb here but I couldn't find any method that gave me that value so I just wanted to suggest to add it in. 

Or do you think it is too easy to accomplish by the user when you supply with `diff()`?

**Comment by nyamsprod** [comment]
@blomdahldaniel  Thanks for the compliment. What your are looking for is `Period::intersect` [which is already documented](http://period.thephpleague.com/api/modifying/#periodintersect)

**Comment by blomdahldaniel** [comment]
Of course you already had it, awesome! Right now, in my head, it doesn't make sence that it is placed under **Modifying**? Cause you don't modify the `$period` that it is compared against when using ìntersect`? You just return a value that is the result of an comparison? Am I totally off?

**Big thanks any how!**

**Comment by nyamsprod** [comment]
no you're not. I will modify the documentation structure then. Do you think the Period::gap method should also be moved ?

**Comment by blomdahldaniel** [comment]
Great! I saw that you also moved `Period::gap` and that makes total sense as well. It is, when you boil it down, also a comparison and not a modifying instance. 

Great and quick respons from you! Thanks!

**Comment by blomdahldaniel** [comment]
But I do think that both `Period::intersect` and `Period::gap` should be placed right beneath `Period::diff`. Now they are separated by the heading *Using durations*.

It might be placed under its own header called **Set theory** or something related to the math expression [wiki#Set_theory](https://en.wikipedia.org/wiki/Set_theory).  Or maybe another header that is more clear. Any how, i think that the 3 of them should be grouped together..?

**Comment by nyamsprod** [comment]
yes your are right I was too quick to apply the changes :+1:

**Comment by blomdahldaniel** [comment]
:+1: 
Great job!  And again, thanks for the good package!
