### ISSUE TITLE
Instantiate from timestamp

### ISSUE THREAD

**Issue by blomdahldaniel** [thephpleague/period#30]
It would be a nice feature to also be able to instantiate a period using unix timestamps. Or is that problematic regarding which timezone that is present?

**Comment by nyamsprod** [comment]
you can already do it 

```php
$period = new League\League\Period('@1455052169', '@1455062169');
```

**Comment by blomdahldaniel** [comment]
Thank you! Where can I read about that in the docs?

**Comment by nyamsprod** [comment]
Just [follow the link](https://github.com/thephpleague/period/blob/gh-pages/definitions.md#arguments) a gave you :)

**Comment by blomdahldaniel** [comment]
omg.. Responded from my phone and did not see that link.

Any how, the docs miss this info. It should be an example under the heading **Instantiation**. So the syntax with the @ symbol should be precent and explained.. And when reading the fact that the
> integer interpreted as the interval expressed in seconds.

still should be entered expressed as a string when creating the period is just weird, especially since there is no explanation or example for this in the docs.

**Comment by nyamsprod** [comment]
>  So the syntax with the @ symbol should be precent and explained.
Why ? This is not an exotic syntax it is the syntax used by [DateTime::construct](http://php.net/manual/en/datetime.construct.php#refsect1-datetime.construct-parameters) 

>   integer interpreted as the interval expressed in seconds.

This is only available for duration so I don't see any possible conflict, one syntax refers to a Timestamp the other to a duration.

**Comment by blomdahldaniel** [comment]
Thank you! Only lack of understanding from my part. 
Thank you for your time and explanations!
