### ISSUE TITLE
Build successful despite of unit test failures

### ISSUE THREAD

**Issue by GodsBoss** [thephpleague/period#36]
See https://travis-ci.org/thephpleague/period/jobs/117922991 - although there is one failed test, the build is successful.

**Comment by nyamsprod** [comment]
@GodsBoss 
I don't know why you removed your PR. I've made some tweaks to it and made a new branch with the fixes (https://github.com/thephpleague/period/tree/bugfix/createfromday). Strangely HHVM does not like the changes maybe it's a bug in HHVM :) I'll investigate

**Comment by nyamsprod** [comment]
@GodsBoss 
Well it seems to be a HHVM bug that was fixed in later version.
https://3v4l.org/jG6uD
the HHVM version in travis is 3.6.6 and the bug is fixed in version 3.10.x and later

**Comment by nyamsprod** [comment]
The bug fix has been merge into the master branch

**Comment by nyamsprod** [comment]
Period 3.2 is out with the fix
