### ISSUE TITLE
Add feature for containsLeapDay()

### ISSUE THREAD

**Issue by rgvcorley** [thephpleague/period#38]
Would be handy to be able to call `containsLeapDay()` on a `Period` object when dealing with periods that might contain leap days.

Specifically at the moment I want to determine if the period is a year long or not, there may be another easier way to do this which I've missed...

**Comment by nyamsprod** [comment]
Adding a new method for such a specific feature seems overkill to me. What's wrong with the Period::contains method ?

I would create a simple function like below If I were you

```php

function containsLeadDay(Period $period)
{
    $date = $period->getStartDate();
    if (!$date->format('L')) {
        $date = $period->getEndDate();
    }

    if (!$date->format('L')) {
        return false;
    }

    $leapDay = date_create_immutable($date->format('Y-02-29'), $date->getTimezone());
    return $period->contains($leapDay);
}
```

**Comment by rgvcorley** [comment]
@nyamsprod I did not know about `L` format! Classic case of rtfm! Thanks a lot :)
