### ISSUE TITLE
How to get dates for same day every week

### ISSUE THREAD

**Issue by Zyles** [thephpleague/period#41]
## Issue summary

If my start date for example is 2016-09-15 19:00, which is a Thursday and I want to figure out the date for every Thursday on wards for the next upcoming N weeks.

If I want every Thursday 4 weeks from now. The dates I want returned are:
2016-09-22
2016-09-29
2016-10-06
2016-10-13

How would this be accomplished?

Thanks.

**Comment by nyamsprod** [comment]
@Zyles what is the relation between your question and the library ? As it stands it looks to me that this is a question to ask on other more appropriate site.

**Comment by Zyles** [comment]
Getting the period between two dates...?

**Comment by nyamsprod** [comment]
I believe that what your are looking for is [already explain in the documentation](http://period.thephpleague.com/api/properties/#iteration-over-a-period)

**Comment by Zyles** [comment]
Ah thank you.
