### ISSUE TITLE
Feature Request -- Find available from multiple periods of time

### ISSUE THREAD

**Issue by jackdpeterson** [thephpleague/period#47]
## Issue summary

Given a collection of Periods where the internal startTime == the lowest value in the collection and the internal endTime == the highest value in the collection, The return of this method would be all of the gaps of unused time (and supporting intersecting / abutting periods). Effectively this would be an inversion of all of the periods in the given collection.

**Comment by nyamsprod** [comment]
this has been discussed in length in #48
