### ISSUE TITLE
Period class next and previous methods when applied to quarter interval return different interval than expected

### ISSUE THREAD

**Issue by andont** [thephpleague/period#55]
## Issue summary

**Period** class **next** and **previous** methods when applied to quarter interval return different interval than expected.

### System informations
| Information | Description |
|--------------|---------|
| League\Period version | 3.3.0 |
| PHP/HHVM version | 7.0.22 |
| OS Platform | Linux |

## Standalone code, or other way to reproduce the problem

```php
<?php

require_once 'vendor/autoload.php';

use League\Period\Period;

$qPrevious = Period::createFromQuarter(2014, 4);
$qCurrent  = Period::createFromQuarter(2015, 1);
$qNext     = Period::createFromQuarter(2015, 2);

var_dump($qCurrent->sameValueAs($qPrevious->next()));
var_dump($qCurrent->sameValueAs($qNext->previous()));
```
### Expected result
```
boolean true
boolean true
```

### Actual result
```
boolean false
boolean false
```

**Comment by nyamsprod** [comment]
@andont This is expected and documented behavior. Please refer to how [Period::previous and Period::next work](period.thephpleague.com/api/modifying/#periodnext).
