### ISSUE TITLE
Unbounded Periods

### ISSUE THREAD

**Issue by bendavies** [thephpleague/period#64]
Hey there,

Any thoughts on supporting unbounded periods, i.e. periods with no start or end date?
This would possibly mirror and be usable with the postgres `tstzrange ` type, which can be unbounded.
https://www.postgresql.org/docs/9.3/static/rangetypes.html#RANGETYPES-INFINITE

Cheers

**Comment by nyamsprod** [comment]
Frankly the thought have crossed my mind but I never went as far as to think about what it would look like. If you have an idea or better an implementation to share that would be a great starting point.

**Comment by nyamsprod** [comment]
Since version 4.4 all boundary types are supported except for unbounded types. Why because it would mean BC break. The current workaround is to declare one endpoint outside your business model making it pseudo unbounded.

**Comment by andreybolonin** [comment]
https://github.com/spatie/period/pull/52
