### ISSUE TITLE
Documentation unclear on upgrade path for next and previous methods

### ISSUE THREAD

**Issue by Rarst** [thephpleague/period#66]
|    Q        |   A
|------------ | ------
| Version     | 4.0

### Question

[3.x to 4.x upgrade guide](https://period.thephpleague.com/4.0/upgrading/#removed-methods) says `next` and `previous` methods are removed as previously deprecated.

I found this a little sudden, since:

1. Version 3.4.0 source doesn’t refer to them as deprecated.
2. v3 documentation neither refers to them as deprecated or suggests replacements to use.

I am not sure if removal was intended (I am assuming so and that deprecation declarations in source were overlooked?) but the upgrade path seems to be missing from either v3 or v4 documentation and perhaps should be covered?

**Comment by nyamsprod** [comment]
Nice catch I've mistaken the add and sub methods to the next and previous one but all theses methods were removed for the same reasons. A PR on the documentation could clarify this issue IMHO. Getting these methods in 4.0 is quite simple you can use the move(Start|End)Date methods to get the same results.

**Comment by Rarst** [comment]
I figured out how to update my specific code with `move()` and explicit duration call. But not too sure how to replicate next/previous behavior when duration argument is omitted (and taken from the object itself).

**Comment by nyamsprod** [comment]
When omitted duration is equal to the period `getDateInterval`

**Comment by Rarst** [comment]
So the `next` equivalent would be:

```php
$nextWeek = $thisWeek->move($thisWeek->getDateInterval());
```

But this doesn't seem to be easily reversible to achieve `previous` ?

**Comment by nyamsprod** [comment]
You can make a negative interval by using the public invert property from a DateInterval object.
