### ISSUE TITLE
Splitting a day period by 10 minutes on daylight savings roll-back day throws LogicException

### ISSUE THREAD

**Issue by isEvrythngTkn** [thephpleague/period#68]
### Bug Report

| Information | Description |
|--------------|---------|
| Version | 4.0.0 |
| PHP version | 7.1.16 |
| OS Platform | MacOS High Sierra 10.13.6 |

#### Summary

If you have a period that spans the day of November 4, 2018 in a timezone where daylight savings is in effect, if you split that period by 10 or 30 minutes, it throws a Logic Exception with the message: "The ending datepoint must be greater or equal to the starting datepoint".

#### Standalone code, or other way to reproduce the problem

I pulled the repo and wrote this test to reproduce the bug.

```
public function testSplitDaylightSavingsDayIntoHours()
{
    date_default_timezone_set('Canada/Central');
    $period = new Period(new DateTime('2018-11-04 00:00:00.000000'), new DateTime('2018-11-05 00:00:00.000000'));
    $splits = $period->split(new DateInterval('PT30M'));
    foreach ($splits as $inner_period) {
        self::assertNotNull($inner_period);
    }
}
```

#### Expected result

To not throw an exception when daylight savings is the cause $startDate > $endDate.

#### Actual result

Throws an exception.

**Comment by nyamsprod** [comment]
@isEvrythngTkn thanks for reporting this bug. A Patch has landed on the master branch also I've added your test to the test suite and also checked that `Period::splitBackward` did not suffer from the same issue. 

Could you have a look and tell me if it's all good for you ? If no I may release a patch fix this week of the week after

**Comment by isEvrythngTkn** [comment]
Thanks very much @nyamsprod. I pulled your latest changes, they look good. Tests all passing. Awesome stuff.

**Comment by nyamsprod** [comment]
version 4.0.1 is out with the bug fix
