### ISSUE TITLE
Complexer period comparisons

### ISSUE THREAD

**Issue by brendt** [thephpleague/period#69]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Proposal

I often find myself having to calculate the diffs or overlaps between multiple periods. This package only handles comparing two periods with each other though, so I made this: https://github.com/spatie/period

I wonder if there's interest in adding more complex date comparisons to this package? Here's an example of one of the things I want to do with it:

```php
/*
 * A                   [====]
 * B                               [========]
 * C         [=====]
 * CURRENT      [========================]
 *
 * DIFF             [=]      [====]
 */

$a = Period::make('2018-01-05', '2018-01-10');
$b = Period::make('2018-01-15', '2018-03-01');
$c = Period::make('2017-01-01', '2018-01-02');

$current = Period::make('2018-01-01', '2018-01-31');

$diff = $current->diff($a, $b, $c);
```

To further clarify when these kind of comparison are useful: imagine an item that can be invoiced. The item has a price per day. Now you want to invoice this item to a customer for a given period: say January. If however, this customer was already invoiced for this item until the half of January, you only want 15 days to be invoiced instead of 31. 

This is a simplified example of what we have to deal with in one of our projects, and I noticed other people also facing the same problems. I think it would be a good addition to this package.

**Comment by nyamsprod** [comment]
@brendt to do what you are requesting it means at least adding a Sequence class to the package which I'm working on right now. the PR for it will hopefully land on separate branch once the code is stable. If you want I can make it public rigth now but the tests are no quite finish.

For now I can tell you that it will have the basic methods from a Sequence object with two additional methods which are `Sequence::getGaps` and `Sequence::getIntersections` which should return the gaps and intersections inside a collection of Period objects. Does that sound good for you ?

Do you want me to publish in a separate branch the work in progress on the `Sequence` class to see if it meets your requirements ? Any input is welcomed 😉

**Comment by brendt** [comment]
@nyamsprod great to hear! I'll definitely want to take a look!

**Comment by nyamsprod** [comment]
you can find it here now https://github.com/thephpleague/period/blob/feature/add-sequence/src/Sequence.php ... again the implementation is not done so yes if you want to improve it be my guess 😉

**Comment by brendt** [comment]
Thanks! There's one thing I'm wondering about: if you sort the intervals by start date to calculate the gaps, is the following scenario covered?

```
sequence:

0) [==================]
1)     [====]
2)                         [=====]

expected gap:

                      [==]

resulting gap:

             [============]
```

I haven't run the code yet, but from reading it, I wonder how this would work if you're relying on a sorted set 🤔

**Comment by nyamsprod** [comment]
@brendt this is a first implementation and tests are missing ... So yeah it is more than possible that your test will not work yet

**Comment by nyamsprod** [comment]
i've just tested you assumption and I do get the expected result :+1: 

```php
<?php

declare(strict_types=1);

use League\Period;
use League\Period\Sequence;
require 'autoload.php';

echo "<pre>", PHP_EOL;

$today = Period\day('2018-11-29');
$week = Period\interval_around('2018-11-29', '4 DAYS');
$next = Period\interval_after('2018-11-29 + 7 DAYS', '1 DAY');

$sequence = new Sequence($week, $today, $next);
$gaps = $sequence->getGaps();
var_export([
    'nb sequence' => count($sequence),
    'nb gaps' => count($gaps), 
    'gap' => $gaps->get(0)->format('Y-m-d'),
]);
```

result

```php
array (
  'nb sequence' => 3,
  'nb gaps' => 1,
  'gap' => '[2018-12-03, 2018-12-06)',
)
```

**Comment by nyamsprod** [comment]
but I'll confess that `Sequence::getIntersections` is still a mess of a implementation :sob:

**Comment by nyamsprod** [comment]
@brendt I've added some of your package tests to the sequence testsuite as well as your example for the getGaps tests and after some fixes seems that my two methods do exactly what you are looking for. Of course more tests are welcomed to complete the testsuite :wink:

**Comment by brendt** [comment]
Oh that's great! Guess I can close this issue now 👍

**Comment by nyamsprod** [comment]
@brendt the Sequence class has landed on the master branch and you can already see [its documentation on the website](https://period.thephpleague.com/4.0/sequence/) If all goes as planned 4.1 should be released next week 😉

**Comment by brendt** [comment]
That's great! I'll do my best to try it out in one of our projects!
