### ISSUE TITLE
Period without end

### ISSUE THREAD

**Issue by andreybolonin** [thephpleague/period#89]
### Feature Request
Any ideas or plans to implement compare periods without end ?

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Proposal

`$period1 = Period::after('2014-01-01');`
`$period2 = Period::after('2014-10-03 08:00:00', 3600);`

`$period1->contains($period2); //return true`

**Comment by nyamsprod** [comment]
@andreybolonin thanks for the question.

For starter I've already partially answer this question on the pinned issue #64 .  Now there are a couple of issues:

- How do you represents the infinite bound (Constants, `NULL`, ... ?)
- should we create a separate UnboundPeriod class or BC break

Also the suggested workaround work almost everytime.

Bottom line if you can correctly come up with an answer to all of the above or better with a PR I'm all for it. But right now the work around works perfectly for me and also is supported by database like postreSQL

**Comment by nyamsprod** [comment]
Closing this issue as it is a duplicate from #64

**Comment by andreybolonin** [comment]
https://github.com/spatie/period/pull/52
