### ISSUE TITLE
Merge sequences. (Logical OR similar to subtract which is logical NOT)

### ISSUE THREAD

**Issue by drmax24** [thephpleague/period#94]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Proposal
We have subtract method for sequences. It represents logical operator NOT.
I need the same logical operator OR. It can be called merge.

**example 1**
```
2 sequences:
== == = ==
==========
output:
==========
```

**example 2**
```
2 sequences:
= = =
 = =
output
=====
```
**example 3**
```
3 sequences:
= = =
=
==
output:
=== =
```

We have a car rental with 10 cars. All cars are similar. Desired rent duration is provided. We want to show a time windows available for rent while combining 10 cars into one. Available periods for each car should cover the same interval and should paint general availability.  I doubt that there is an existing feature that would allows this. 

Correct me if i'm wrong. Please provide some advice. Also I hope to discuss it further. Thank you in advance!

**Comment by nyamsprod** [comment]
since I don't exactly understand what you want I can only tell you to read the documentation and found a solution with the exposed Sequence method. If not you can always submit a PR with the requested feature implemented.
