### ISSUE TITLE
Missing Period in Sequence intersections.

### ISSUE THREAD

**Issue by Ormira** [thephpleague/period#95]
### Bug Report

| Information | Description |
|--------------|---------|
| Version | 4.9.0 |
| PHP version | 7.3 |
| OS Platform | Linux |

#### Summary

Trying to get the intersections between a Period overlapping two other only return the first one.

#### Standalone code, or other way to reproduce the problem

The following test doesn't pass :
```
    /**
     * Intersections test 3.
     *
     *        [-------------------------)
     *             [-----)
     *                   [------)
     *
     *                 =
     *
     *             [-----)[-----)
     */
    public function testGetIntersections3(): void
    {
        $sequence = new Sequence(
            new Period('2020-01-09 22:00:00', '2020-01-10 00:00:00'),
            new Period('2020-01-10 00:00:00', '2020-01-10 06:00:00'),
            new Period('2020-01-09 18:25:00', '2020-01-10 07:10:05')
        );
        $intersections = $sequence->getIntersections();
        self::assertCount(2, $intersections);
        self::assertSame('[2020-01-09 22:00:00, 2020-01-10 00:00:00)', $intersections->get(0)->format('Y-m-d H:i:s'));
        self::assertSame('[2020-01-10 00:00:00, 2020-01-10 07:10:05)', $intersections->get(1)->format('Y-m-d H:i:s'));
    }
```
This one is OK :
```
    /**
     * Intersections test 4.
     *
     *        [--------------)
     *             [-----)
     *                   [------)
     *
     *                 =
     *
     *             [-----)[---)
     */
    public function testGetIntersections4(): void
    {
        $sequence = new Sequence(
            new Period('2020-01-09 22:00:00', '2020-01-10 00:00:00'),
            new Period('2020-01-10 00:00:00', '2020-01-10 06:00:00'),
            new Period('2020-01-09 18:25:00', '2020-01-10 01:10:05')
        );
        $intersections = $sequence->getIntersections();
        self::assertCount(2, $intersections);
        self::assertSame('[2020-01-09 22:00:00, 2020-01-10 00:00:00)', $intersections->get(0)->format('Y-m-d H:i:s'));
        self::assertSame('[2020-01-10 00:00:00, 2020-01-10 01:10:05)', $intersections->get(1)->format('Y-m-d H:i:s'));
    }
```
#### Expected result

In testGetIntersections3(), $sequence->getIntersections() should return a Sequence with two Period equals to the two smaller ones.

#### Actual result

Only the first smaller Period is part of the returned Sequence : [2020-01-09 22:00:00, 2020-01-10 00:00:00)

**Comment by nyamsprod** [comment]
the current PR should fix the issue but also changes how the intersections method is implemented and update some tests @Ormira could you confirm the new behaviour. thanks in advance.

**Comment by Ormira** [comment]
While this does resolve the problem I was facing, as I'll never have more than two Period overlaping, I'm not sure doing It by changing how it work when it happen is the way to go.
That said, I checked the changed test and without the modification to Sequence.php the method intersections() was sensitive to the order of the Periods in the Sequence.

**Comment by nyamsprod** [comment]
@Ormira indeed the patch does not just addressed your issue but improve the way `intersections` was implemented so it's not just your use case that I want to fix but the method overall result 😉

**Comment by Ormira** [comment]
Seems good to me then !
All my use case tests have passed with the change.

**Comment by nyamsprod** [comment]
bug fix merged into the master branch
